### ISSUE TITLE
TypeError: t.binary is undefined

### ISSUE THREAD

**Issue by clochix** [cozy-labs/cozy-music#57]
Error reported by @dkm, see cozy/cozy-files#426

**Comment by poupotte** [comment]
This issue should be fixed with new version : 0.4.3

**Comment by dkm** [comment]
Thanks, I'll be able to test when my cozy has this update available (atm, it's still 0.4.2)

**Comment by dkm** [comment]
I've been able to install 0.4.3 by giving the direct github url. The app is installed, but now, when opening it, I only get : 
'Not Found'

Not sure why, and of course, can't really say that bug is fix on my side...

**Comment by dkm** [comment]
Update still not available in 'Store' in my cozy. Do I need to do something to force the update ?

**Comment by clochix** [comment]
Sorry @dkm, we forgot to publish version 0.4.3 on npm (we are currently updating our publication workflow and sometime make mistakes). The update should now be available. Just restart the Home (`cozy-monitor restart home`) and wait a little bit to see it.

**Comment by dkm** [comment]
ok. After updating the app, I can finally see my 10 music files. Thanks !

You can close the bug AFAIC.
